export const currencies = [
  "AUD",
  "CAD",
  "CNY",
  "CZK",
  "DKK",
  "EUR",
  "GBP",
  "JPY",
  "NOK",
  "NZD",
  "USD",
];

export const currencyDecimal = {
  AUD: 2,
  CAD: 2,
  CNY: 2,
  CZK: 2,
  DKK: 2,
  EUR: 2,
  GBP: 2,
  JPY: 0,
  NOK: 2,
  NZD: 2,
  USD: 2,
};

export const currencyPairRates = {
  AUDUSD: 0.8371,
  CADUSD: 0.8711,
  USDCNY: 6.1715,
  EURUSD: 1.2315,
  GBPUSD: 1.5683,
  NZDUSD: 0.775,
  USDJPY: 119.95,
  EURCZK: 27.6028,
  EURDKK: 7.4405,
  EURNOK: 8.6651,
};

export const currencyTable = {
  AUD: {
    AUD: "1:1",
    CAD: "USD",
    CNY: "USD",
    CZK: "USD",
    DKK: "USD",
    EUR: "USD",
    GBP: "USD",
    JPY: "USD",
    NOK: "USD",
    NZD: "USD",
    USD: "D",
  },
  CAD: {
    AUD: "USD",
    CAD: "1:1",
    CNY: "USD",
    CZK: "USD",
    DKK: "USD",
    EUR: "USD",
    GBP: "USD",
    JPY: "USD",
    NOK: "USD",
    NZD: "USD",
    USD: "D",
  },
  CNY: {
    AUD: "USD",
    CAD: "USD",
    CNY: "1:1",
    CZK: "USD",
    DKK: "USD",
    EUR: "USD",
    GBP: "USD",
    JPY: "USD",
    NOK: "USD",
    NZD: "USD",
    USD: "Inv",
  },
  CZK: {
    AUD: "USD",
    CAD: "USD",
    CNY: "USD",
    CZK: "1:1",
    DKK: "EUR",
    EUR: "Inv",
    GBP: "USD",
    JPY: "USD",
    NOK: "EUR",
    NZD: "USD",
    USD: "EUR",
  },
  DKK: {
    AUD: "USD",
    CAD: "USD",
    CNY: "USD",
    CZK: "EUR",
    DKK: "1:1",
    EUR: "Inv",
    GBP: "USD",
    JPY: "USD",
    NOK: "EUR",
    NZD: "USD",
    USD: "EUR",
  },
  EUR: {
    AUD: "USD",
    CAD: "USD",
    CNY: "USD",
    CZK: "D",
    DKK: "D",
    EUR: "1:1",
    GBP: "USD",
    JPY: "USD",
    NOK: "D",
    NZD: "USD",
    USD: "D",
  },
  GBP: {
    AUD: "USD",
    CAD: "USD",
    CNY: "USD",
    CZK: "USD",
    DKK: "USD",
    EUR: "USD",
    GBP: "1:1",
    JPY: "USD",
    NOK: "USD",
    NZD: "USD",
    USD: "D",
  },
  JPY: {
    AUD: "USD",
    CAD: "USD",
    CNY: "USD",
    CZK: "USD",
    DKK: "USD",
    EUR: "USD",
    GBP: "USD",
    JPY: "1:1",
    NOK: "USD",
    NZD: "USD",
    USD: "Inv",
  },
  NOK: {
    AUD: "USD",
    CAD: "USD",
    CNY: "USD",
    CZK: "EUR",
    DKK: "EUR",
    EUR: "Inv",
    GBP: "USD",
    JPY: "USD",
    NOK: "1:1",
    NZD: "USD",
    USD: "EUR",
  },
  NZD: {
    AUD: "USD",
    CAD: "USD",
    CNY: "USD",
    CZK: "USD",
    DKK: "USD",
    EUR: "USD",
    GBP: "USD",
    JPY: "USD",
    NOK: "USD",
    NZD: "1:1",
    USD: "D",
  },
  USD: {
    AUD: "Inv",
    CAD: "Inv",
    CNY: "D",
    CZK: "EUR",
    DKK: "EUR",
    EUR: "Inv",
    GBP: "Inv",
    JPY: "D",
    NOK: "EUR",
    NZD: "Inv",
    USD: "1:1",
  },
};
